const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const dotenv = require('dotenv');
dotenv.config();

const User = require('./models/User');
const Job = require('./models/Job');

const MONGO_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/jobportal';

const JOBS = [
  // ── IT Jobs ──────────────────────────────────────────────────
  {
    title: 'Frontend Developer',
    description: 'Build responsive UIs using React and Tailwind CSS. Work closely with designers to implement pixel-perfect interfaces and ensure cross-browser compatibility.',
    company: 'TechNova Inc.',
    location: 'Remote',
    type: 'Full-time',
    salary: { min: 70000, max: 110000, currency: 'USD' },
    skills: ['React', 'Tailwind CSS', 'TypeScript', 'Git'],
    requirements: ['2+ years React experience', 'Strong CSS skills', 'REST API integration'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Backend Engineer',
    description: 'Design and build scalable REST APIs using Node.js and PostgreSQL. Own microservices architecture and AWS deployments.',
    company: 'CloudStack Ltd.',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: { min: 80000, max: 130000, currency: 'USD' },
    skills: ['Node.js', 'PostgreSQL', 'AWS', 'Docker'],
    requirements: ['3+ years Node.js', 'Database design experience', 'AWS certification preferred'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Data Analyst',
    description: 'Analyze large datasets to uncover business insights. Build dashboards in Power BI and automate reporting pipelines using Python and SQL.',
    company: 'DataValley',
    location: 'Bangalore',
    type: 'Full-time',
    salary: { min: 60000, max: 95000, currency: 'USD' },
    skills: ['Python', 'SQL', 'Power BI', 'Excel'],
    requirements: ['Experience with data visualization', 'SQL proficiency', 'Statistics knowledge'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Cybersecurity Analyst',
    description: 'Monitor, detect, and respond to security incidents. Conduct penetration testing and vulnerability assessments across enterprise systems.',
    company: 'SecureNet Systems',
    location: 'Remote',
    type: 'Full-time',
    salary: { min: 90000, max: 140000, currency: 'USD' },
    skills: ['SIEM', 'Penetration Testing', 'Linux', 'Network Security'],
    requirements: ['CISSP or CEH certification', 'Experience with SIEM tools', 'Incident response knowledge'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'DevOps Engineer',
    description: 'Maintain CI/CD pipelines, manage Kubernetes clusters, and automate infrastructure provisioning using Terraform and Ansible.',
    company: 'Inframatic',
    location: 'Chennai',
    type: 'Full-time',
    salary: { min: 85000, max: 125000, currency: 'USD' },
    skills: ['Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
    requirements: ['Kubernetes experience required', 'Jenkins or GitHub Actions', 'Linux administration'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'UI/UX Designer',
    description: 'Create wireframes, prototypes, and high-fidelity designs in Figma. Conduct user research and usability testing to improve product experience.',
    company: 'PixelCraft Studio',
    location: 'Mumbai',
    type: 'Contract',
    salary: { min: 55000, max: 90000, currency: 'USD' },
    skills: ['Figma', 'Prototyping', 'User Research', 'Adobe XD'],
    requirements: ['Portfolio required', 'Experience with design systems', 'Collaboration with developers'],
    experience: '1-2 years',
    category: 'Design',
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Machine Learning Engineer',
    description: 'Develop and deploy ML models for recommendation systems and NLP pipelines. Work with large-scale data infrastructure on GCP.',
    company: 'AIForge Labs',
    location: 'Bangalore',
    type: 'Full-time',
    salary: { min: 100000, max: 160000, currency: 'USD' },
    skills: ['Python', 'TensorFlow', 'NLP', 'GCP'],
    requirements: ['Masters or PhD preferred', 'Published ML research a plus', 'Strong Python skills'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Full Stack Developer',
    description: 'Work across the entire stack — from React frontends to Node.js APIs and MongoDB databases. Participate in agile sprints and code reviews.',
    company: 'StartupHub',
    location: 'Remote',
    type: 'Remote',
    salary: { min: 75000, max: 120000, currency: 'USD' },
    skills: ['React', 'Node.js', 'MongoDB', 'REST APIs'],
    requirements: ['Full stack portfolio', '3+ years total experience', 'Startup mindset'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Mobile App Developer (React Native)',
    description: 'Build cross-platform mobile applications for iOS and Android. Integrate REST APIs, push notifications, and in-app purchase flows.',
    company: 'AppWorks Pvt Ltd',
    location: 'Pune',
    type: 'Full-time',
    salary: { min: 65000, max: 105000, currency: 'USD' },
    skills: ['React Native', 'JavaScript', 'iOS', 'Android'],
    requirements: ['Published apps on Play Store or App Store', 'Redux experience', 'API integration'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Cloud Solutions Architect',
    description: 'Design enterprise cloud architectures on AWS. Lead migration projects and ensure security, scalability, and cost optimization.',
    company: 'NexGen Cloud',
    location: 'Delhi',
    type: 'Full-time',
    salary: { min: 120000, max: 180000, currency: 'USD' },
    skills: ['AWS', 'Cloud Architecture', 'Security', 'Cost Optimization'],
    requirements: ['AWS Solutions Architect certification required', '7+ years IT experience', 'Strong communication'],
    experience: '5+ years',
    category: 'Technology',
    deadline: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
  },

  {
    title: 'QA Engineer',
    description: 'Design and execute test plans for web and mobile applications. Automate regression tests using Selenium and Cypress.',
    company: 'BugFree Solutions',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: { min: 55000, max: 90000, currency: 'USD' },
    skills: ['Selenium', 'Cypress', 'JIRA', 'API Testing'],
    requirements: ['2+ years QA experience', 'Automation framework knowledge', 'Agile methodology'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Blockchain Developer',
    description: 'Develop and audit smart contracts on Ethereum. Build DeFi protocols and integrate Web3.js into frontend applications.',
    company: 'ChainWorks Technologies',
    location: 'Remote',
    type: 'Full-time',
    salary: { min: 110000, max: 170000, currency: 'USD' },
    skills: ['Solidity', 'Ethereum', 'Web3.js', 'Smart Contracts'],
    requirements: ['Strong Solidity skills', 'DeFi protocol experience', 'Security audit experience preferred'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Data Engineer',
    description: 'Build and maintain data pipelines using Apache Spark and Kafka. Design data warehouses on Snowflake and BigQuery for analytics teams.',
    company: 'StreamData Inc.',
    location: 'Bangalore',
    type: 'Full-time',
    salary: { min: 90000, max: 140000, currency: 'USD' },
    skills: ['Apache Spark', 'Kafka', 'Snowflake', 'Python'],
    requirements: ['Data pipeline experience required', 'SQL and Python proficiency', 'Cloud data warehouse knowledge'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Site Reliability Engineer',
    description: 'Ensure 99.9% uptime for production systems. Implement observability using Prometheus and Grafana, and lead incident response.',
    company: 'Uptime Systems',
    location: 'Chennai',
    type: 'Full-time',
    salary: { min: 95000, max: 150000, currency: 'USD' },
    skills: ['Prometheus', 'Grafana', 'Kubernetes', 'Go'],
    requirements: ['SRE or DevOps background', 'On-call experience', 'Strong problem-solving skills'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Product Manager',
    description: 'Own the product roadmap for a SaaS B2B platform. Work with engineering, design, and sales to ship features that drive growth.',
    company: 'SaaSify',
    location: 'Mumbai',
    type: 'Full-time',
    salary: { min: 100000, max: 160000, currency: 'USD' },
    skills: ['Product Roadmap', 'Agile', 'User Stories', 'Data Analysis'],
    requirements: ['3+ years product management', 'Technical background preferred', 'Strong communication skills'],
    experience: '3-5 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Embedded Systems Engineer',
    description: 'Develop firmware for IoT devices using C and C++. Work with RTOS, communication protocols like MQTT and BLE, and hardware bring-up.',
    company: 'IoTech Devices',
    location: 'Pune',
    type: 'Full-time',
    salary: { min: 70000, max: 115000, currency: 'USD' },
    skills: ['C', 'C++', 'RTOS', 'MQTT', 'BLE'],
    requirements: ['Embedded C experience required', 'Hardware bring-up knowledge', 'RTOS familiarity'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Business Intelligence Developer',
    description: 'Create interactive dashboards and reports using Tableau and Power BI. Build ETL pipelines to consolidate data from multiple sources.',
    company: 'InsightIQ Analytics',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: { min: 65000, max: 100000, currency: 'USD' },
    skills: ['Tableau', 'Power BI', 'ETL', 'SQL'],
    requirements: ['BI tool certification preferred', 'Strong SQL skills', 'Business analysis experience'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Android Developer',
    description: 'Build native Android apps in Kotlin. Implement Material Design, integrate REST APIs, and publish to the Google Play Store.',
    company: 'DroidWorks',
    location: 'Bangalore',
    type: 'Full-time',
    salary: { min: 60000, max: 100000, currency: 'USD' },
    skills: ['Kotlin', 'Android SDK', 'Jetpack Compose', 'REST APIs'],
    requirements: ['Published apps on Play Store', 'Jetpack Compose experience', 'MVVM architecture knowledge'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Network Engineer',
    description: 'Configure and maintain enterprise LAN/WAN infrastructure. Manage Cisco routers, switches, firewalls, and VPN solutions.',
    company: 'NetCore Solutions',
    location: 'Delhi',
    type: 'Full-time',
    salary: { min: 55000, max: 95000, currency: 'USD' },
    skills: ['Cisco', 'CCNA', 'Firewalls', 'VPN', 'BGP/OSPF'],
    requirements: ['CCNA certification required', 'Hands-on Cisco experience', 'Network troubleshooting skills'],
    experience: '1-2 years',
    category: 'Technology',
    deadline: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Technical Content Writer',
    description: 'Write developer documentation, API guides, blog posts, and tutorials. Work closely with engineering teams to make complex concepts accessible.',
    company: 'DevWrite Studios',
    location: 'Remote',
    type: 'Part-time',
    salary: { min: 35000, max: 60000, currency: 'USD' },
    skills: ['Technical Writing', 'Markdown', 'API Docs', 'Git'],
    requirements: ['Strong English writing skills', 'Developer background preferred', 'Portfolio of technical writing'],
    experience: 'Entry Level',
    category: 'Technology',
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
  },

  // ── Non-IT Jobs ───────────────────────────────────────────────
  {
    title: 'Logistics Coordinator',
    description: 'Manage end-to-end supply chain operations including inventory tracking, vendor coordination, and timely dispatch scheduling.',
    company: 'SwiftMove Logistics',
    location: 'Delhi',
    type: 'Full-time',
    salary: { min: 35000, max: 60000, currency: 'USD' },
    skills: ['Supply Chain', 'Inventory Management', 'ERP', 'Excel'],
    requirements: ['Logistics or supply chain degree', 'ERP software experience', 'Attention to detail'],
    experience: '1-2 years',
    category: 'Other',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Staff Nurse',
    description: 'Provide patient care in ICU and general wards. Administer medications, monitor vitals, and coordinate with doctors for treatment plans.',
    company: 'Apollo Hospitals',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: { min: 30000, max: 50000, currency: 'USD' },
    skills: ['Patient Care', 'ICU', 'Medication Administration', 'Documentation'],
    requirements: ['B.Sc Nursing required', 'State nursing council registration', 'ICU experience preferred'],
    experience: 'Entry Level',
    category: 'Healthcare',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'High School Mathematics Teacher',
    description: 'Teach Maths for grades 9–12 following CBSE curriculum. Prepare lesson plans, conduct assessments, and mentor students for board exams.',
    company: 'Greenwood Academy',
    location: 'Pune',
    type: 'Full-time',
    salary: { min: 25000, max: 45000, currency: 'USD' },
    skills: ['Mathematics', 'Curriculum Planning', 'CBSE', 'Student Mentoring'],
    requirements: ['B.Ed degree required', 'Teaching experience preferred', 'Strong subject knowledge'],
    experience: 'Entry Level',
    category: 'Education',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Executive Chef',
    description: 'Lead kitchen operations for a 5-star hotel. Oversee menu planning, staff training, food cost control, and HACCP compliance.',
    company: 'The Grand Meridian Hotel',
    location: 'Goa',
    type: 'Full-time',
    salary: { min: 65000, max: 115000, currency: 'USD' },
    skills: ['Menu Planning', 'Kitchen Management', 'HACCP', 'Team Leadership'],
    requirements: ['Culinary degree', '8+ years kitchen experience', 'Luxury hospitality background'],
    experience: '5+ years',
    category: 'Other',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Civil Site Engineer',
    description: 'Supervise residential and commercial construction projects. Ensure structural safety, manage subcontractors, and report progress.',
    company: 'BuildRight Constructions',
    location: 'Mumbai',
    type: 'Full-time',
    salary: { min: 40000, max: 75000, currency: 'USD' },
    skills: ['AutoCAD', 'Site Supervision', 'RCC Design', 'MS Project'],
    requirements: ['B.Tech Civil Engineering', 'Site experience required', 'AutoCAD proficiency'],
    experience: '1-2 years',
    category: 'Engineering',
    deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Bank Branch Manager',
    description: 'Manage daily branch operations, meet business targets, ensure compliance with RBI regulations, and lead a team of 15+ staff.',
    company: 'IndiaFirst Bank',
    location: 'Kolkata',
    type: 'Full-time',
    salary: { min: 80000, max: 130000, currency: 'USD' },
    skills: ['Banking Operations', 'Team Leadership', 'KYC/AML', 'P&L Management'],
    requirements: ['MBA Finance or Banking', '5+ years banking experience', 'Regulatory compliance knowledge'],
    experience: '5+ years',
    category: 'Finance',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Digital Marketing Manager',
    description: 'Plan and execute multi-channel digital campaigns including SEO, Google Ads, Meta Ads, and email marketing to drive lead generation.',
    company: 'BrandRocket Agency',
    location: 'Remote',
    type: 'Full-time',
    salary: { min: 50000, max: 90000, currency: 'USD' },
    skills: ['SEO', 'Google Ads', 'Social Media', 'Email Marketing'],
    requirements: ['3+ years digital marketing', 'Google Ads certified preferred', 'Analytics proficiency'],
    experience: '3-5 years',
    category: 'Marketing',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Sales Executive',
    description: 'Generate B2B leads, conduct product demos, and close deals for enterprise software solutions. Meet monthly revenue targets.',
    company: 'SalesForce Pro',
    location: 'Bangalore',
    type: 'Full-time',
    salary: { min: 40000, max: 80000, currency: 'USD' },
    skills: ['B2B Sales', 'CRM', 'Negotiation', 'Cold Calling'],
    requirements: ['Sales experience required', 'Excellent communication', 'Target-driven mindset'],
    experience: '1-2 years',
    category: 'Sales',
    deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'HR Recruiter',
    description: 'Handle end-to-end recruitment for IT and non-IT roles. Source candidates, conduct HR interviews, and manage onboarding processes.',
    company: 'PeopleFirst HR Solutions',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: { min: 30000, max: 55000, currency: 'USD' },
    skills: ['Talent Acquisition', 'HR Interviews', 'LinkedIn Sourcing', 'HRMS'],
    requirements: ['MBA HR preferred', 'ATS experience', 'Strong interpersonal skills'],
    experience: 'Entry Level',
    category: 'Other',
    deadline: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Graphic Designer',
    description: 'Create visual content for social media, print, and digital campaigns. Work with brand guidelines to produce consistent, high-quality designs.',
    company: 'CreativeHive Studio',
    location: 'Chennai',
    type: 'Contract',
    salary: { min: 28000, max: 50000, currency: 'USD' },
    skills: ['Adobe Illustrator', 'Photoshop', 'Canva', 'Brand Design'],
    requirements: ['Portfolio required', 'Proficiency in Adobe Suite', 'Ability to meet deadlines'],
    experience: '1-2 years',
    category: 'Design',
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Pharmacist',
    description: 'Dispense medications, counsel patients on drug usage, and maintain pharmacy inventory. Ensure compliance with drug regulations.',
    company: 'MedPlus Pharmacy',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: { min: 32000, max: 55000, currency: 'USD' },
    skills: ['Drug Dispensing', 'Patient Counseling', 'Inventory Management', 'Pharmaceutical Knowledge'],
    requirements: ['B.Pharma or M.Pharma required', 'State pharmacy license', 'Attention to detail'],
    experience: 'Entry Level',
    category: 'Healthcare',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Financial Analyst',
    description: 'Prepare financial models, conduct variance analysis, and support budgeting and forecasting for a mid-size manufacturing company.',
    company: 'FinCore Advisors',
    location: 'Mumbai',
    type: 'Full-time',
    salary: { min: 60000, max: 100000, currency: 'USD' },
    skills: ['Financial Modeling', 'Excel', 'Forecasting', 'Variance Analysis'],
    requirements: ['CA/CFA or MBA Finance', 'Advanced Excel skills', '2+ years finance experience'],
    experience: '1-2 years',
    category: 'Finance',
    deadline: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Event Coordinator',
    description: 'Plan and execute corporate events, product launches, and conferences. Manage vendors, budgets, and on-site logistics.',
    company: 'EventPro India',
    location: 'Bangalore',
    type: 'Full-time',
    salary: { min: 30000, max: 55000, currency: 'USD' },
    skills: ['Event Planning', 'Vendor Management', 'Budgeting', 'Communication'],
    requirements: ['Event management degree preferred', 'Excellent organizational skills', 'Ability to handle pressure'],
    experience: '1-2 years',
    category: 'Other',
    deadline: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Legal Associate',
    description: 'Draft contracts, handle corporate compliance, and assist senior lawyers with litigation support and due diligence.',
    company: 'LexCorp Law Firm',
    location: 'Delhi',
    type: 'Full-time',
    salary: { min: 45000, max: 80000, currency: 'USD' },
    skills: ['Contract Drafting', 'Corporate Law', 'Due Diligence', 'Legal Research'],
    requirements: ['LLB required', 'Bar Council enrollment', 'Strong drafting skills'],
    experience: 'Entry Level',
    category: 'Other',
    deadline: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Physical Therapist',
    description: 'Assess and treat patients with musculoskeletal disorders. Design individualized rehabilitation plans and monitor recovery progress.',
    company: 'RehabCare Clinic',
    location: 'Chennai',
    type: 'Full-time',
    salary: { min: 35000, max: 60000, currency: 'USD' },
    skills: ['Physiotherapy', 'Rehabilitation', 'Patient Assessment', 'Exercise Therapy'],
    requirements: ['BPT degree required', 'State registration mandatory', 'Hands-on clinical experience'],
    experience: 'Entry Level',
    category: 'Healthcare',
    deadline: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Content Writer',
    description: 'Write SEO-optimized blog articles, website copy, and social media content for lifestyle and fashion brands.',
    company: 'Inkflow Media',
    location: 'Remote',
    type: 'Part-time',
    salary: { min: 20000, max: 40000, currency: 'USD' },
    skills: ['SEO Writing', 'Copywriting', 'WordPress', 'Social Media Content'],
    requirements: ['Excellent English writing', 'SEO knowledge', 'Portfolio of published articles'],
    experience: 'Entry Level',
    category: 'Marketing',
    deadline: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Operations Manager',
    description: 'Oversee daily operations of a manufacturing unit. Manage production targets, quality control, workforce scheduling, and vendor relations.',
    company: 'PrecisionMake Industries',
    location: 'Pune',
    type: 'Full-time',
    salary: { min: 70000, max: 120000, currency: 'USD' },
    skills: ['Operations Management', 'Lean Manufacturing', 'Quality Control', 'Leadership'],
    requirements: ['MBA Operations or Engineering degree', '5+ years manufacturing experience', 'Lean/Six Sigma preferred'],
    experience: '5+ years',
    category: 'Other',
    deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'School Principal',
    description: 'Lead academic and administrative operations of a CBSE school. Drive curriculum quality, staff development, and parent engagement.',
    company: 'Sunrise International School',
    location: 'Kolkata',
    type: 'Full-time',
    salary: { min: 60000, max: 100000, currency: 'USD' },
    skills: ['Academic Leadership', 'Staff Management', 'CBSE Compliance', 'Strategic Planning'],
    requirements: ['M.Ed or equivalent required', '10+ years in education', 'Leadership experience mandatory'],
    experience: '5+ years',
    category: 'Education',
    deadline: new Date(Date.now() + 35 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Real Estate Sales Agent',
    description: 'Help clients buy, sell, and rent residential and commercial properties. Build a client pipeline, conduct site visits, and negotiate deals.',
    company: 'PropNest Realty',
    location: 'Hyderabad',
    type: 'Full-time',
    salary: { min: 25000, max: 70000, currency: 'USD' },
    skills: ['Real Estate', 'Negotiation', 'Client Relationship', 'Market Analysis'],
    requirements: ['Real estate license preferred', 'Strong networking skills', 'Target-driven attitude'],
    experience: 'Entry Level',
    category: 'Sales',
    deadline: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
  },
  {
    title: 'Graphic Designer',
    description: 'Create visual content for social media, print, and digital campaigns. Work with brand guidelines to produce consistent, high-quality designs.',
    company: 'CreativeHive Studio',
    location: 'Chennai',
    type: 'Contract',
    salary: { min: 28000, max: 50000, currency: 'USD' },
    skills: ['Adobe Illustrator', 'Photoshop', 'Canva', 'Brand Design'],
    requirements: ['Portfolio required', 'Proficiency in Adobe Suite', 'Ability to meet deadlines'],
    experience: '1-2 years',
    category: 'Design',
    deadline: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
  },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('✅ Connected to MongoDB');

  // Create or find seed employer
  let employer = await User.findOne({ email: 'employer@careerwave.com' });
  if (!employer) {
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash('employer123', salt);
    employer = await User.create({
      name: 'CareerWave Admin',
      email: 'employer@careerwave.com',
      password: hashedPassword,
      role: 'employer',
      company: 'CareerWave',
    });
    console.log('✅ Seed employer created: employer@careerwave.com / employer123');
  } else {
    console.log('ℹ️  Seed employer already exists');
  }

  // Remove old seeded jobs (same employer)
  await Job.deleteMany({ employer: employer._id });
  console.log('🗑️  Old seeded jobs cleared');

  // Insert all jobs
  const jobsWithEmployer = JOBS.map((j) => ({ ...j, employer: employer._id }));
  await Job.insertMany(jobsWithEmployer);
  console.log(`✅ ${JOBS.length} jobs inserted successfully!`);

  await mongoose.disconnect();
  console.log('🔌 Disconnected. Seeding complete.');
}

seed().catch((err) => {
  console.error('❌ Seeding failed:', err.message);
  process.exit(1);
});
